# Use a specific version of Node.js for consistency
FROM node:21-alpine3.18

# Set working directory
WORKDIR /app

# Copy only necessary files first to leverage Docker cache effectively
COPY package.json tsconfig.json ./

# Install dependencies
RUN npm install && npm install -g nodemon cross-env

# Copy the rest of the application code
COPY src ./src

# Expose the application port
EXPOSE 4003

# Set the default command
CMD ["npm", "run", "dev"]
